### ISSUE TITLE
Unable to download from Drive and Azure

### ISSUE THREAD

**Issue by Ludvig-Joborn** [Sanyuan-Chen/CSS_with_Conformer#11]
Hello!

I am unable to download the model weights from both Drive and Azure. Is there any possibility of making them available again? (Preferably uploaded to the repository for stable long-term storage)

Best regards, Ludvig J.

**Comment by Sanyuan-Chen** [comment]
Hi @Ludvig-Joborn , I have updated the Azure link, please try again~

**Comment by Ludvig-Joborn** [comment]
The new links work perfectly, thank you! :grin: 

@Sanyuan-Chen

**Comment by ichi131** [comment]
@Sanyuan-Chen @Ludvig-Joborn It looks like this link is no longer working. Could you please update it?
