### ISSUE TITLE
How to train without pretrained model?

### ISSUE THREAD

**Issue by ermu-tech** [Sanyuan-Chen/CSS_with_Conformer#3]
请问如何不使用预训练模型来完成分离呢？如何在你的代码中介入评价指标呢？期待您的回复，谢谢！

**Comment by Sanyuan-Chen** [comment]
hi,

如果不使用预训练模型参数，你可以直接将这两行（[#L46](https://github.com/Sanyuan-Chen/CSS_with_Conformer/blob/87435ac0e47766877e8cfb484a0f52a25dd22500/separate.py#L46), [L47](https://github.com/Sanyuan-Chen/CSS_with_Conformer/blob/87435ac0e47766877e8cfb484a0f52a25dd22500/separate.py#L47)）注释后运行即可~

由于训练脚本是微软公司内部代码，我们在这里只能提供inference的代码~

如果使用LibrCSS数据集对分离模型进行评价，你可以首先按照README的Get Started得到分离后的音频，然后再按照[LibriCSS的官方脚本](https://github.com/chenzhuo1011/libri_css)来评价分离后的音频。
如果使用其它的数据集和评价指标，你可以将输入mix-scp参数替换成你的路径地址，进行inference得到分离后的音频，再对输出音频进行相应的评价。

**Comment by ermu-tech** [comment]
您好，我在注释掉您说的那两行代码后提示以下错误：
![2021-10-29 16-37-27屏幕截图](https://user-images.githubusercontent.com/58473058/139404375-f0e3e944-377a-4715-a47a-d076196f95d9.png)

**Comment by Sanyuan-Chen** [comment]
hi, 你需要首先下载README里的预训练模型文件（包含预训练模型的参数文件(*.tar)和config文件(*.yaml)），然后在运行python命令时将--checkpoint 设置为下载模型对应的文件夹。当此脚本正常运行时，它会首先加载文件夹里的config文件来定义模型类别和初始化模型参数，再加载文件夹里的预训练模型的参数文件并赋值给初始化的模型。当你注释这两行代码之后，此脚本不会读取并使用预训练模型的参数，不过仍然需要读取文件夹中的config文件。如果你希望自定义模型的配置，可以直接在config文件中作对应的修改。
