### ISSUE TITLE
403 forbidden when downloading the pre-trained model & dataset

### ISSUE THREAD

**Issue by songtaoshi** [Sanyuan-Chen/CSS_with_Conformer#4]
Hi @Sanyuan-Chen, 
I get 403 response when downloading the pre-trained model * dataset, what's wrong with the cloud server?  
![image](https://user-images.githubusercontent.com/20240391/141477328-0898dfca-a0a3-4b2c-a110-9ffe9446af51.png)

**Comment by Sanyuan-Chen** [comment]
Hi @songtaoshi ,
I think it's because the google drive link is forbidden on your server. I have updated an additional download option of Microsoft Azure Storage in README. Please have a try on this new option~
