### ISSUE TITLE
关于conformer.py中的RelativePositionalEncoding类

### ISSUE THREAD

**Issue by AIHHU** [Sanyuan-Chen/CSS_with_Conformer#6]
请问maxlen属性指的是什么？

**Comment by Sanyuan-Chen** [comment]
你好~
RelativePositionalEncoding中的maxlen是表示最大相对位置距离的超参数。对于输入序列中的两个位置，如果他们的相对位置距离d小于maxlen，则我们能够找出相应的embedding表示此距离d；如果他们的相对位置距离d距离大于maxlen，则我们使用maxlen对应的embedding来表示此相对位置距离。
