### ISSUE TITLE
长语音分离

### ISSUE THREAD

**Issue by Chen-jia621** [Sanyuan-Chen/CSS_with_Conformer#8]
你好，请问长语音分离的时候怎么设置num_speaker参数呢？

**Comment by Sanyuan-Chen** [comment]
你好~ 
num_speaker超参数需要在模型训练时和测试时保持一致。我们的模型在训练时num_speaker超参数设置为2，因此使用我们的模型测试时也需要将此超参数设置为2。
如果你想要实现很长输入语音的分离，可以参考我们的文章或者[此文章](https://www.microsoft.com/en-us/research/uploads/prod/2018/08/Interspeech2018-CameraReady.pdf)中介绍的Chunk-wise processing方法。在此方法中，由于我们依次只对2.4s的一个chunk进行语音分离，所以此chunk中很大概率只包含两位说话者，我们只需将num_speaker超参数设置为2即可。

**Comment by Chen-jia621** [comment]
你好！很高兴收到您的回复！我想知道假如一段语音里面是不重叠的多个人的声音，怎么把同一个人的声音拼接到一起呢，因为我看这篇论文里面主要是针对相邻的块进行处理，然后之前看的有论文里提出了speaker inventory方法，所以想知道这篇文章里是怎么解决这个问题的。谢谢！



---原始邮件---
发件人: "Sanyuan Chen ***@***.***&gt;
发送时间: 2022年3月23日(周三) 中午12:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Sanyuan-Chen/CSS_with_Conformer] 长语音分离 (Issue #8)




 
你好~
 num_speaker超参数需要在模型训练时和测试时保持一致。我们的模型在训练时num_speaker超参数设置为2，因此使用我们的模型测试时也需要将此超参数设置为2。
 如果你想要实现很长输入语音的分离，可以参考我们的文章或者此文章中介绍的Chunk-wise processing方法。在此方法中，由于我们依次只对2.4s的一个chunk进行语音分离，所以此chunk中很大概率只包含两位说话者，我们只需将num_speaker超参数设置为2即可。

**Comment by Sanyuan-Chen** [comment]
你好，我们这篇文章主要是处理重叠多说话者的分离问题，并没有考虑到对于说话者具体的信息进行建模。因此如果一段语音中某个说话者持续不断地在说话，我们可以通过将相邻chunk的输出进行stitching操作使得这个说话者的声音可以拼接在一起；而如果这个说话者在语音中间隔了一段时间没有说话，那么我们的方法则不能保证在两个相隔很远的chunk中这个说话者的声音都可以被排序到相同的通道中~

**Comment by Chen-jia621** [comment]
非常高兴收到你的回复！谢谢你的解答！



---原始邮件---
发件人: "Sanyuan Chen ***@***.***&gt;
发送时间: 2022年3月24日(周四) 下午2:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Sanyuan-Chen/CSS_with_Conformer] 长语音分离 (Issue #8)




 
你好，我们这篇文章主要是处理重叠多说话者的分离问题，并没有考虑到对于说话者具体的信息进行建模。因此如果一段语音中某个说话者持续不断地在说话，我们可以通过将相邻chunk的输出进行stitching操作使得这个说话者的声音可以拼接在一起；而如果这个说话者在语音中间隔了一段时间没有说话，那么我们的方法则不能保证在两个相隔很远的chunk中这个说话者的声音都可以被排序到相同的通道中~
